// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Triperis.Data;

#nullable disable

namespace Triperis.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220403164313_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Triperis.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Aprasymas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Defektai")
                        .HasColumnType("bit");

                    b.Property<int>("Galia")
                        .HasColumnType("int");

                    b.Property<int>("Kaina")
                        .HasColumnType("int");

                    b.Property<string>("KebuloTipas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KuroTipas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marke")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Metai")
                        .HasColumnType("int");

                    b.Property<string>("Modelis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Parduotas")
                        .HasColumnType("bit");

                    b.Property<string>("PavaruDeze")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rida")
                        .HasColumnType("int");

                    b.Property<string>("Spalva")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("VariklioTuris")
                        .HasColumnType("float");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
